# Generated by Django 2.0 on 2017-12-24 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Toothpick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToothpickOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.NullBooleanField(default=True)),
                ('own_start_at', models.DateTimeField(auto_now_add=True)),
                ('own_end_at', models.DateTimeField(blank=True, null=True)),
                ('toothpick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Toothpick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='toothpick',
            name='owners',
            field=models.ManyToManyField(through='core.ToothpickOwnership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='toothpickownership',
            unique_together={('toothpick', 'user', 'enabled')},
        ),
    ]
